[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.lyze237:gdx-UnBox2D:$unbox2dVersion"
  api "space.earlygrey:shapedrawer:$shapeDrawerVersion"
  api 'com.google.code.gson:gson:2.10.1'
  implementation 'com.google.code.gson:gson:2.10.1'
  testImplementation 'org.mockito:mockito-core:4.0.0'
  testImplementation 'com.badlogicgames.gdx:gdx-backend-headless:1.10.0'
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.mockito:mockito-core:4.0.0'

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}
